# -*- coding: utf-8 -*-
# RANDOM_SEED = 123
#
#
# NN_LAYERS = [13,8,3]
#
# LEARN_PERCENTAGE = 0.8
#
# EPOCHS = 200
# LEARNING_RATE = 0.3
# ALPHA_MOMENTO = 0.1

ROWS_TO_SKIP = 0
ROWS_COUNT = 302

# MLP
RANDOM_SEED = 21
LEARN_PERCENTAGE = 0.95
WINDOW_SIZE = 5

NEURONS_COUNT_KOHONEN = 8
NN_LAYERS = [NEURONS_COUNT_KOHONEN, 8, 3]
EPOCHS = 67
LEARNING_RATE = 0.5
ALPHA_MOMENTO = 0.9

# KOHONEN
ALPHA_KOHONEN = 0.01
EPOCHS_KOHONEN = 100
NORMALIZE_PARAMETER = 3
